unbind C-b
set-option -g prefix C-s
bind C-s send-prefix

# start window index at 1
set-option -g base-index 1

set-option -g history-limit 10000
setw -g monitor-activity on
set -g visual-activity on

set-option -g mouse on


bind r source-file ~/.tmux.conf \; display "config reloaded!"

# Pane navigation using vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes using arrow keys
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5


# Load tmux plugins
run-shell "${MYCONFIGS}/tmux/tmux-plugins/tmux-resurrect/resurrect.tmux"
run-shell "${MYCONFIGS}/tmux/tmux-plugins/tmux-nova/nova.tmux"
