
TMUX_CONF_DIR="${MYCONFIGS}/tmux/configs"
TMUX_PLUGINS_DIR="${MYCONFIGS}/tmux/tmux-plugins"

# Load configs
source "$TMUX_CONF_DIR/theme.conf"
# TODO: Move to keybinds.conf
# source "$TMUX_CONF_DIR/keybinds.conf"

unbind C-b
set-option -g prefix C-s
bind C-s send-prefix

# start window index at 1
set-option -g base-index 1

set-option -g history-limit 10000
setw -g monitor-activity on
set -g visual-activity on

setw -g mode-keys vi
set-option -g mouse on

set-option -g renumber-windows on

bind r source-file ~/.tmux.conf \; display "config reloaded!"

# Pane navigation using vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes using arrow keys
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

setw -g mode-keys vi
set-option -g set-titles on
set-option -g set-titles-string "#{session_name} - #{window_name}"

# Tmux popup panes
bind C-y display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \



# Load tmux plugins

run-shell "$TMUX_PLUGINS_DIR/tmux-resurrect/resurrect.tmux"
